title: Software Testing and Testing Automation with Python
logo: /assets/img/unit_testing.gif
description: Contents for the software testing and testing automation with python short course.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
