# Create full conda environment for development, including some useful tools
name: python-testing
channels:
  - conda-forge
dependencies:
  - python=3
  - numpy
  - scipy
  - matplotlib
  - pytest>=2.4
  - pytest-cov
  - pytest-flake8
  - pytest-mpl
  - pytest-runner
  - flake8-builtins!=1.4.0
  - flake8-comprehensions=1.4.1
  - flake8-copyright
  - flake8-docstrings
  - flake8-import-order
  - flake8-mutable
  - flake8-pep3101
  - flake8-print
  - flake8-quotes
  - pep8-naming
  - vcrpy
